# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itsel

scrape_configs:
  - job_name: 'product-microservice'  # Name of the job for your service
    metrics_path: '/actuator/prometheus'  # Path to the metrics endpoint
    scrape_interval: 5s  # How often to scrape this service
    static_configs:
      - targets: ['host.docker.internal:8082']  # Replace with the host and port of your microservice
  - job_name: 'user-microservice'  # Name of the job for your service
    metrics_path: '/actuator/prometheus'  # Path to the metrics endpoint
    scrape_interval: 5s  # How often to scrape this service
    static_configs:
      - targets: ['host.docker.internal:8081']  # Replace with the host and port of your microservice
  - job_name: "prometheus"  # Name of the job for Prometheus's own metrics
    static_configs: